[package]
name = "tempConverter"
version = "0.1.0"
edition = "2021"

[dependencies]
random-number = "0.1.9"
zip = "2.2.2"
reqwest = { version = "0.11", features = ["blocking", "json"] }
select = "0.5"
regex = "1.11.1"
age = "0.11.1"
secrecy = "0.10.3"